(in-package :mu-cl-resources)

(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "rdfs" "http://www.w3.org/2000/01/rdf-schema#")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "task" "http://redpencil.data.gift/vocabularies/tasks/")
(add-prefix "schema" "https://schema.org/")